name: personal-website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Test Docker image
        run: docker run -d -p 80:80 $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: |
          gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} \
          --image $IMAGE_NAME \
          --region ${{ secrets.GCP_REGION}} \
          --platform managed \
          --min-instances ${{ secrets.GCP_MIN_INSTANCES}} \
          --max-instances ${{ secrets.GCP_MAX_INSTANCES }} \
          --concurrency ${{ secrets.GCP_CONCURRENCY }} \
          --port 80 \
          --cpu ${{ secrets.GCP_CPU }} \
          --memory ${{ secrets.GCP_MEMORY }} \
          --allow-unauthenticated
